version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
  build:
    commands:
      - echo "Building React frontend..."
      - npm run build
artifacts:
  files:
    - '**/*'
    - '!node_modules/**'
  base-directory: frontend/build   # <-- ensures build output is picked up
