version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing backend dependencies..."
      - cd backend
      - npm install
  build:
    commands:
      - echo "Backend build phase (no build step needed)"
artifacts:
  files:
    - '**/*'
    - '!node_modules/**'
